# Generated by Django 3.0 on 2021-01-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fex_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='freeze_balanca',
            field=models.IntegerField(default=0),
        ),
    ]
