# Generated by Django 3.0 on 2021-01-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_advert', models.CharField(choices=[('sellers', 'sellers'), ('buyers', 'buyers')], default='', max_length=50, verbose_name='type of advert')),
                ('title', models.CharField(blank=True, max_length=254, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('r1', 'new'), ('r2', 'active'), ('r3', 'in_trash'), ('r4', 'completed')], default='r1', max_length=2, verbose_name='status')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('active_until_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active until data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
            },
        ),
    ]
