# Generated by Django 3.0 on 2021-01-26 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('message', models.TextField(blank=True, verbose_name='Description')),
                ('planed_date', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.AlterModelOptions(
            name='advertfile',
            options={'verbose_name': 'AdvertFile', 'verbose_name_plural': 'AdvertFiles'},
        ),
        migrations.AddField(
            model_name='advertfile',
            name='advert_file',
            field=models.FileField(default='', upload_to='C:\\Work_2021\\work\\freelance_exchange\\fex/media_root/'),
        ),
        migrations.AddField(
            model_name='advertfile',
            name='advert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advert.Advert', verbose_name='advert_id'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='ReplyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_file', models.FileField(default='', upload_to='C:\\Work_2021\\work\\freelance_exchange\\fex/media_root/')),
                ('reply_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advert.Reply', verbose_name='reply_id')),
            ],
            options={
                'verbose_name': 'ReplyFile',
                'verbose_name_plural': 'ReplyFiles',
            },
        ),
        migrations.AddField(
            model_name='reply',
            name='advert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advert.Advert', verbose_name='advert_id'),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
