# Generated by Django 3.0 on 2021-01-27 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20210126_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='planed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planed date'),
        ),
    ]
