# Generated by Django 3.0 on 2021-01-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20210128_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='advert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.Advert', verbose_name='Advert id'),
        ),
    ]
