# Generated by Django 3.0 on 2021-01-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20210128_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='advert_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.Advert', verbose_name='Advert id'),
        ),
    ]
