# Generated by Django 3.0 on 2021-01-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20210129_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertfile',
            name='advert_id',
        ),
    ]
