# Generated by Django 3.0 on 2021-02-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_remove_advertfile_advert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertfile',
            name='advert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advert.Advert', verbose_name='advert_id'),
        ),
        migrations.AlterField(
            model_name='advertfile',
            name='advert_file',
            field=models.FileField(default='', upload_to='C:\\Work_2021\\work\\freelance_exchange\\fex/media/'),
        ),
        migrations.AlterField(
            model_name='replyfile',
            name='reply_file',
            field=models.FileField(default='', upload_to='C:\\Work_2021\\work\\freelance_exchange\\fex/media/'),
        ),
    ]
