# Generated by Django 3.0 on 2021-02-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_auto_20210201_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advert.AdvertFile', verbose_name='Advert file'),
        ),
        migrations.AddField(
            model_name='advert',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advert.Reply', verbose_name='Reply'),
        ),
        migrations.AddField(
            model_name='advert',
            name='rep_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advert.ReplyFile', verbose_name='Reply file'),
        ),
    ]
