# Generated by Django 3.0 on 2021-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20210204_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='advert_file',
        ),
        migrations.AddField(
            model_name='advert',
            name='advert_file',
            field=models.ManyToManyField(blank=True, null=True, to='advert.AdvertFile', verbose_name='Advert file'),
        ),
    ]
