# Generated by Django 3.0 on 2021-02-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0010_auto_20210205_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='rep_file',
        ),
        migrations.AddField(
            model_name='reply',
            name='rep_file',
            field=models.ManyToManyField(blank=True, null=True, to='advert.ReplyFile', verbose_name='Reply file'),
        ),
        migrations.RemoveField(
            model_name='advert',
            name='rep',
        ),
        migrations.AddField(
            model_name='advert',
            name='rep',
            field=models.ManyToManyField(blank=True, null=True, to='advert.Reply', verbose_name='Reply'),
        ),
    ]
