# Generated by Django 3.0 on 2021-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210114_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='freeze_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='freeze balance'),
        ),
    ]
